### ISSUE TITLE
Issue decompiling for 1.14.3

### ISSUE THREAD

**Issue by jLynx** [ThisTestUser/MCPFixer#4]
So I have tried a few things.
First time I was able to decompile successfully but it failed to recompile.

At this stage I forgot to do the step ```For 1.14 and up, search for IgnorePkg, and delete com from the list.```
The reason it failed to compile was listed here:
[recompile Error.txt](https://github.com/ThisTestUser/MCPFixer/files/3352677/recompile.Error.txt)

I then realized I missed that step and tried again.

I first tried removing the ```IgnorePkg``` line from mcp.cfg but then comands.py complained as it couldn't find that key/line.

So then I went and commented out every line that contained ```IgnorePkg``` in commands.py (There were 11 instances found in total).

I then got this error:

```
== MCP 9.40 (data: 9.42, client: 1.14.3, server: 1.14.3) ==
"scalac" is not found on the PATH.  Scala files will not be recompiled
# found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle co
nfig, rg, ss
!! Modified jar detected. Unpredictable results !!
== Decompiling client using fernflower ==
> Creating SRGs
> Applying SpecialSource
> Applying MCInjector
> Creating renamed srg
> Filtering classes
FATAL ERROR
Traceback (most recent call last):
  File "runtime\decompile.py", line 144, in decompile
    joined=only_joined)
  File "A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\1.14.3\mcp940\runtime\m
cp.py", line 45, in decompile_side
    commands.filterffjar(side)
  File "A:\Users\Joel\Documents\Code\Minecraft\MCP Fixer\1.14.3\mcp940\runtime\c
ommands.py", line 1370, in filterffjar
    for p in self.ignorepkg:
AttributeError: 'Commands' object has no attribute 'ignorepkg'
Press any key to continue . . .
```

Are you able to explain that step again as I must have done something wrong?

**Comment by jLynx** [comment]
Im stupid and need to learn to read. Delete **COM**, not the whole line...

**Comment by jLynx** [comment]
On a side note. this works fine with 1.14.3, so you can update your wiki message at the bottom to say that version number :)
