### ISSUE TITLE
 MCP [1.8.8] Cannot decompile both Client and Server 

### ISSUE THREAD

**Issue by 47e** [ThisTestUser/MCPFixer#5]
Hey, ive been trying to decompile minecraft 1.8.8 cause im trying to make a client, However i get errors and i don't know how to solve them, if someone could help me it would be great, thanks!

> == MCP 9.18 (data: 9.18, client: 1.8.8, server: 1.8.8) ==
> Searching for javac.exe in C:\Program Files
"scalac" is not found on the PATH.  Scala files will not be recompiled
# found ff, ff patches, srgs, name csvs, doc csvs, param csvs, astyle, astyle config, rg, ss
== Decompiling client using fernflower ==
> Creating SRGs
> Applying SpecialSource
> Applying MCInjector
> Creating renamed srg
> Filtering classes
> Decompiling
> Unpacking jar
> Copying sources
> Applying fernflower fixes
> Applying patches
'runtime\bin\applydiff.exe -p1 -u -i ..\..\temp\temp.patch -d src\minecraft' failed : 1

== ERRORS FOUND ==

1 out of 1 hunk FAILED -- saving rejects to file 'net\minecraft\util\Cartesian.jav#'
==================

> Cleaning comments
- Done in 296.62 seconds
== Reformating client ==
> Cleaning sources
> Replacing OpenGL constants
> Reformating sources
- Done in 37.89 seconds
== Updating client ==
> Adding javadoc
> Renaming sources
- Done in 41.92 seconds
== Decompiling server using fernflower ==
> Creating SRGs
> Applying SpecialSource
> Applying MCInjector
> Creating renamed srg
> Filtering classes
> Decompiling
> Unpacking jar
> Copying sources
> Applying fernflower fixes
> Applying patches
'runtime\bin\applydiff.exe -p1 -u -i ..\..\temp\temp.patch -d src\minecraft_server' failed : 1

== ERRORS FOUND ==

1 out of 1 hunk FAILED -- saving rejects to file 'net\minecraft\util\Cartesian.jav#'
==================

> Cleaning comments
- Done in 111.68 seconds
== Reformating server ==
> Cleaning sources
> Reformating sources
- Done in 25.08 seconds
== Updating server ==
> Adding javadoc
> Renaming sources
- Done in 26.25 seconds
== Recompiling client ==
> Cleaning bin
> Recompiling
'"C:\Program Files\Java\jdk-11.0.3\bin\javac" -Xlint:-options -deprecation -g -source 1.6 -target 1.6 -classpath "jars\versions\1.8.8\1.8.8.jar;lib;lib\*;jars\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;jars\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar;jars\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;jars\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar;jars\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;jars\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;jars\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;jars\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;jars\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;jars\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;jars\libraries\com\google\guava\guava\17.0\guava-17.0.jar;jars\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;jars\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;jars\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;jars\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;jars\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;jars\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;jars\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;jars\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;jars\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;jars\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;jars\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;jars\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;jars\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;jars\libraries\com\mojang\realms\1.7.39\realms-1.7.39.jar;jars\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar;jars\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;jars\libraries\com\mojang\netty\1.6\netty-1.6.jar;jars\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar;jars\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;jars\libraries\tv\twitch\twitch-platform\6.5\twitch-platform-6.5-natives-windows-64.jar;jars\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar;jars\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;jars\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar" -sourcepath src\minecraft -d bin\minecraft @temp\java_src_client.txt' failed : 1

== ERRORS FOUND in JAVA CODE ==

src\minecraft\net\minecraft\util\ObjectIntIdentityMap.java:21: error: incompatible types: Object cannot be converted to T
            this.objectList.add((Object)null);
                                ^

  where T is a type-variable:
    T extends Object declared in class ObjectIntIdentityMap
src\minecraft\net\minecraft\tileentity\TileEntity.java:108: warning: [deprecation] newInstance() in Class has been deprecated
                tileentity = (TileEntity)oclass.newInstance();
                                               ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft\net\minecraft\inventory\Container.java:39: error: incompatible types: Object cannot be converted to ItemStack
        this.inventoryItemStacks.add((Object)null);
                                     ^

src\minecraft\net\minecraft\network\NetHandlerPlayServer.java:445: error: incompatible types: Set<Object> cannot be converted to Set<EnumFlags>
        this.setPlayerLocation(x, y, z, yaw, pitch, Collections.emptySet());
                                                                        ^

src\minecraft\net\minecraft\network\NetworkSystem.java:78: error: incompatible types: List<Object> cannot be converted to List<ChannelFuture>
    private final List<ChannelFuture> endpoints = Collections.synchronizedList(Lists.newArrayList());
                                                                              ^

src\minecraft\net\minecraft\network\NetworkSystem.java:79: error: incompatible types: List<Object> cannot be converted to List<NetworkManager>
    private final List<NetworkManager> networkManagers = Collections.synchronizedList(Lists.newArrayList());
                                                                                     ^

src\minecraft\net\minecraft\network\EnumConnectionState.java:291: warning: [deprecation] newInstance() in Class has been deprecated
        return oclass == null ? null : (Packet)oclass.newInstance();
                                                     ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft\net\minecraft\network\EnumConnectionState.java:332: warning: [deprecation] newInstance() in Class has been deprecated
                        oclass.newInstance();
                              ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft\net\minecraft\entity\item\EntityMinecart.java:97: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(17, new Integer(0));
                                       ^

src\minecraft\net\minecraft\entity\item\EntityMinecart.java:98: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(18, new Integer(1));
                                       ^

src\minecraft\net\minecraft\entity\item\EntityMinecart.java:99: warning: [deprecation] Float(float) in Float has been deprecated
        this.dataWatcher.addObject(19, new Float(0.0F));
                                       ^

src\minecraft\net\minecraft\entity\item\EntityMinecart.java:100: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(20, new Integer(0));
                                       ^

src\minecraft\net\minecraft\entity\item\EntityMinecart.java:101: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(21, new Integer(6));
                                       ^

src\minecraft\net\minecraft\block\BlockRedstoneTorch.java:27: error: incompatible types: ArrayList<Object> cannot be converted to List<Toggle>
            toggles.put(worldIn, Lists.newArrayList());
                                                   ^

src\minecraft\net\minecraft\block\state\pattern\FactoryBlockPattern.java:26: error: incompatible types: Predicate<Object> cannot be converted to Predicate<BlockWorldState>
        this.symbolMap.put(' ', Predicates.alwaysTrue());
                                                     ^

src\minecraft\net\minecraft\block\state\pattern\FactoryBlockPattern.java:56: error: incompatible types: Object cannot be converted to Predicate<BlockWorldState>
                            this.symbolMap.put(Character.valueOf(c0), (Object)null);
                                                                      ^

src\minecraft\net\minecraft\client\Minecraft.java:811: error: incompatible types: List<Object> cannot be converted to List<ResourcePackRepository.Entry>
            this.mcResourcePackRepository.setRepositories(Collections.emptyList());
                                                                               ^

src\minecraft\net\minecraft\client\renderer\texture\TextureAtlasSprite.java:382: error: incompatible types: Object cannot be converted to int[][]
                this.framesTextureData.add((Object)null);
                                           ^

src\minecraft\net\minecraft\world\gen\FlatGeneratorInfo.java:300: error: incompatible types: HashMap<Object,Object> cannot be converted to Map<String,String>
                        flatgeneratorinfo.getWorldFeatures().put("village", Maps.newHashMap());
                                                                                           ^

src\minecraft\net\minecraft\world\gen\FlatGeneratorInfo.java:325: error: incompatible types: HashMap<Object,Object> cannot be converted to Map<String,String>
        flatgeneratorinfo.getWorldFeatures().put("village", Maps.newHashMap());
                                                                           ^

src\minecraft\net\minecraft\client\gui\GuiFlatPresets.java:176: error: incompatible types: HashMap<Object,Object> cannot be converted to Map<String,String>
                flatgeneratorinfo.getWorldFeatures().put(s, Maps.newHashMap());
                                                                           ^

src\minecraft\net\minecraft\client\network\OldServerPinger.java:50: error: incompatible types: List<Object> cannot be converted to List<NetworkManager>
    private final List<NetworkManager> pingDestinations = Collections.synchronizedList(Lists.newArrayList());
                                                                                      ^

src\minecraft\net\minecraft\client\gui\GuiScreenRealmsProxy.java:18: error: incompatible types: List<Object> cannot be converted to List<GuiButton>
        super.buttonList = Collections.synchronizedList(Lists.newArrayList());
                                                       ^

src\minecraft\net\minecraft\client\renderer\block\model\ModelBlock.java:55: error: incompatible types: List<Object> cannot be converted to List<BlockPart>
        this(parentLocationIn, Collections.emptyList(), texturesIn, ambientOcclusionIn, gui3dIn, cameraTransformsIn);
                                                    ^

src\minecraft\net\minecraft\entity\passive\EntityBat.java:29: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\monster\EntityBlaze.java:55: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\item\EntityBoat.java:56: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(17, new Integer(0));
                                       ^

src\minecraft\net\minecraft\entity\item\EntityBoat.java:57: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(18, new Integer(1));
                                       ^

src\minecraft\net\minecraft\entity\item\EntityBoat.java:58: warning: [deprecation] Float(float) in Float has been deprecated
        this.dataWatcher.addObject(19, new Float(0.0F));
                                       ^

src\minecraft\net\minecraft\entity\monster\EntitySpider.java:67: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\monster\EntityEnderman.java:84: warning: [deprecation] Short(short) in Short has been deprecated
        this.dataWatcher.addObject(16, new Short((short)0));
                                       ^

src\minecraft\net\minecraft\entity\monster\EntityEnderman.java:85: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(17, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\monster\EntityEnderman.java:86: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(18, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\passive\EntityWolf.java:131: warning: [deprecation] Float(float) in Float has been deprecated
        this.dataWatcher.addObject(18, new Float(this.getHealth()));
                                       ^

src\minecraft\net\minecraft\entity\passive\EntityWolf.java:132: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(19, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\passive\EntityWolf.java:133: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(20, new Byte((byte)EnumDyeColor.RED.getMetadata()));
                                       ^

src\minecraft\net\minecraft\entity\passive\EntitySheep.java:111: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\monster\EntitySkeleton.java:76: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(13, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\entity\boss\EntityWither.java:79: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(17, new Integer(0));
                                       ^

src\minecraft\net\minecraft\entity\boss\EntityWither.java:80: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(18, new Integer(0));
                                       ^

src\minecraft\net\minecraft\entity\boss\EntityWither.java:81: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(19, new Integer(0));
                                       ^

src\minecraft\net\minecraft\entity\boss\EntityWither.java:82: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(20, new Integer(0));
                                       ^

src\minecraft\net\minecraft\client\resources\FallbackResourceManager.java:122: warning: [deprecation] finalize() in Object has been deprecated
        protected void finalize() throws Throwable
                       ^

src\minecraft\net\minecraft\client\resources\FallbackResourceManager.java:129: warning: [deprecation] finalize() in Object has been deprecated
            super.finalize();
                 ^

src\minecraft\net\minecraft\client\resources\FileResourcePack.java:108: warning: [deprecation] finalize() in Object has been deprecated
    protected void finalize() throws Throwable
                   ^

src\minecraft\net\minecraft\client\resources\FileResourcePack.java:111: warning: [deprecation] finalize() in Object has been deprecated
        super.finalize();
             ^

src\minecraft\net\minecraft\client\resources\FolderResourcePack.java:36: error: reference to listFiles is ambiguous
            for (File file2 : file1.listFiles(DirectoryFileFilter.DIRECTORY))
                                   ^

  both method listFiles(FilenameFilter) in File and method listFiles(FileFilter) in File match
src\minecraft\net\minecraft\client\resources\model\SimpleBakedModel.java:116: error: incompatible types: ArrayList<Object> cannot be converted to List<BakedQuad>
                this.builderFaceQuads.add(Lists.newArrayList());
                                                            ^

src\minecraft\net\minecraft\command\CommandSpreadPlayers.java:138: error: incompatible types: Object cannot be converted to Team
                set.add((Object)null);
                        ^

src\minecraft\net\minecraft\entity\ai\attributes\ModifiableAttributeInstance.java:33: error: incompatible types: HashSet<Object> cannot be converted to Set<AttributeModifier>
            this.mapByOperation.put(Integer.valueOf(i), Sets.newHashSet());
                                                                       ^

src\minecraft\net\minecraft\entity\item\EntityMinecartFurnace.java:41: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft\net\minecraft\realms\RealmsServerStatusPinger.java:28: error: incompatible types: List<Object> cannot be converted to List<NetworkManager>
    private final List<NetworkManager> connections = Collections.synchronizedList(Lists.newArrayList());
                                                                                 ^

src\minecraft\net\minecraft\util\Cartesian.java:56: error: incompatible types: List<Object> cannot be converted to List<T>
            return Arrays.asList((Object[])p_apply_1_);
                                ^

  where T is a type-variable:
    T extends Object declared in class GetList
src\minecraft\net\minecraft\world\gen\structure\MapGenStructureIO.java:50: warning: [deprecation] newInstance() in Class has been deprecated
                structurestart = (StructureStart)oclass.newInstance();
                                                       ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft\net\minecraft\world\gen\structure\MapGenStructureIO.java:81: warning: [deprecation] newInstance() in Class has been deprecated
                structurecomponent = (StructureComponent)oclass.newInstance();
                                                               ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft\net\minecraft\world\gen\structure\StructureMineshaftPieces.java:611: error: cannot find symbol
            for (lvt_5_1_ = 0; k < this.boundingBox.getXSize(); k = k + 4)
                 ^

  symbol:   variable lvt_5_1_
  location: class Room
src\minecraft\net\minecraft\world\storage\ThreadedFileIOBase.java:11: error: incompatible types: List<Object> cannot be converted to List<IThreadedFileIO>
    private List<IThreadedFileIO> threadedIOQueue = Collections.synchronizedList(Lists.newArrayList());
                                                                                ^

24 errors
33 warnings
==================

Initial client recompile failed, correct source then run updatemd5
== Recompiling server ==
> Cleaning bin
> Recompiling
'"C:\Program Files\Java\jdk-11.0.3\bin\javac" -Xlint:-options -deprecation -g -source 1.6 -target 1.6 -classpath "lib;lib\*;jars\minecraft_server.1.8.8.jar" -sourcepath src\minecraft_server -d bin\minecraft_server @temp\java_src_server.txt' failed : 1

== ERRORS FOUND in JAVA CODE ==

src\minecraft_server\net\minecraft\util\ObjectIntIdentityMap.java:21: error: incompatible types: Object cannot be converted to T
            this.objectList.add((Object)null);
                                ^

  where T is a type-variable:
    T extends Object declared in class ObjectIntIdentityMap
src\minecraft_server\net\minecraft\tileentity\TileEntity.java:108: warning: [deprecation] newInstance() in Class has been deprecated
                tileentity = (TileEntity)oclass.newInstance();
                                               ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft_server\net\minecraft\inventory\Container.java:38: error: incompatible types: Object cannot be converted to ItemStack
        this.inventoryItemStacks.add((Object)null);
                                     ^

src\minecraft_server\net\minecraft\network\NetHandlerPlayServer.java:445: error: incompatible types: Set<Object> cannot be converted to Set<EnumFlags>
        this.setPlayerLocation(x, y, z, yaw, pitch, Collections.emptySet());
                                                                        ^

src\minecraft_server\net\minecraft\network\NetworkSystem.java:74: error: incompatible types: List<Object> cannot be converted to List<ChannelFuture>
    private final List<ChannelFuture> endpoints = Collections.synchronizedList(Lists.newArrayList());
                                                                              ^

src\minecraft_server\net\minecraft\network\NetworkSystem.java:75: error: incompatible types: List<Object> cannot be converted to List<NetworkManager>
    private final List<NetworkManager> networkManagers = Collections.synchronizedList(Lists.newArrayList());
                                                                                     ^

src\minecraft_server\net\minecraft\network\EnumConnectionState.java:291: warning: [deprecation] newInstance() in Class has been deprecated
        return oclass == null ? null : (Packet)oclass.newInstance();
                                                     ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft_server\net\minecraft\network\EnumConnectionState.java:332: warning: [deprecation] newInstance() in Class has been deprecated
                        oclass.newInstance();
                              ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft_server\net\minecraft\entity\item\EntityMinecart.java:94: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(17, new Integer(0));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityMinecart.java:95: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(18, new Integer(1));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityMinecart.java:96: warning: [deprecation] Float(float) in Float has been deprecated
        this.dataWatcher.addObject(19, new Float(0.0F));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityMinecart.java:97: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(20, new Integer(0));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityMinecart.java:98: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(21, new Integer(6));
                                       ^

src\minecraft_server\net\minecraft\block\BlockRedstoneTorch.java:27: error: incompatible types: ArrayList<Object> cannot be converted to List<Toggle>
            toggles.put(worldIn, Lists.newArrayList());
                                                   ^

src\minecraft_server\net\minecraft\block\state\pattern\FactoryBlockPattern.java:26: error: incompatible types: Predicate<Object> cannot be converted to Predicate<BlockWorldState>
        this.symbolMap.put(' ', Predicates.alwaysTrue());
                                                     ^

src\minecraft_server\net\minecraft\block\state\pattern\FactoryBlockPattern.java:56: error: incompatible types: Object cannot be converted to Predicate<BlockWorldState>
                            this.symbolMap.put(Character.valueOf(c0), (Object)null);
                                                                      ^

src\minecraft_server\net\minecraft\command\CommandSpreadPlayers.java:138: error: incompatible types: Object cannot be converted to Team
                set.add((Object)null);
                        ^

src\minecraft_server\net\minecraft\entity\passive\EntityWolf.java:131: warning: [deprecation] Float(float) in Float has been deprecated
        this.dataWatcher.addObject(18, new Float(this.getHealth()));
                                       ^

src\minecraft_server\net\minecraft\entity\passive\EntityWolf.java:132: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(19, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\passive\EntityWolf.java:133: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(20, new Byte((byte)EnumDyeColor.RED.getMetadata()));
                                       ^

src\minecraft_server\net\minecraft\entity\ai\attributes\ModifiableAttributeInstance.java:32: error: incompatible types: HashSet<Object> cannot be converted to Set<AttributeModifier>
            this.mapByOperation.put(Integer.valueOf(i), Sets.newHashSet());
                                                                       ^

src\minecraft_server\net\minecraft\entity\boss\EntityWither.java:79: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(17, new Integer(0));
                                       ^

src\minecraft_server\net\minecraft\entity\boss\EntityWither.java:80: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(18, new Integer(0));
                                       ^

src\minecraft_server\net\minecraft\entity\boss\EntityWither.java:81: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(19, new Integer(0));
                                       ^

src\minecraft_server\net\minecraft\entity\boss\EntityWither.java:82: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(20, new Integer(0));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityBoat.java:53: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(17, new Integer(0));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityBoat.java:54: warning: [deprecation] Integer(int) in Integer has been deprecated
        this.dataWatcher.addObject(18, new Integer(1));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityBoat.java:55: warning: [deprecation] Float(float) in Float has been deprecated
        this.dataWatcher.addObject(19, new Float(0.0F));
                                       ^

src\minecraft_server\net\minecraft\entity\item\EntityMinecartFurnace.java:41: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\monster\EntityBlaze.java:55: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\monster\EntitySpider.java:67: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\monster\EntityEnderman.java:84: warning: [deprecation] Short(short) in Short has been deprecated
        this.dataWatcher.addObject(16, new Short((short)0));
                                       ^

src\minecraft_server\net\minecraft\entity\monster\EntityEnderman.java:85: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(17, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\monster\EntityEnderman.java:86: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(18, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\monster\EntitySkeleton.java:76: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(13, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\passive\EntityBat.java:29: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\entity\passive\EntitySheep.java:110: warning: [deprecation] Byte(byte) in Byte has been deprecated
        this.dataWatcher.addObject(16, new Byte((byte)0));
                                       ^

src\minecraft_server\net\minecraft\server\dedicated\DedicatedServer.java:41: error: incompatible types: List<Object> cannot be converted to List<ServerCommand>
    private final List<ServerCommand> pendingCommandList = Collections.synchronizedList(Lists.newArrayList());
                                                                                       ^

src\minecraft_server\net\minecraft\util\Cartesian.java:56: error: incompatible types: List<Object> cannot be converted to List<T>
            return Arrays.asList((Object[])p_apply_1_);
                                ^

  where T is a type-variable:
    T extends Object declared in class GetList
src\minecraft_server\net\minecraft\world\gen\FlatGeneratorInfo.java:300: error: incompatible types: HashMap<Object,Object> cannot be converted to Map<String,String>
                        flatgeneratorinfo.getWorldFeatures().put("village", Maps.newHashMap());
                                                                                           ^

src\minecraft_server\net\minecraft\world\gen\FlatGeneratorInfo.java:325: error: incompatible types: HashMap<Object,Object> cannot be converted to Map<String,String>
        flatgeneratorinfo.getWorldFeatures().put("village", Maps.newHashMap());
                                                                           ^

src\minecraft_server\net\minecraft\world\gen\structure\MapGenStructureIO.java:50: warning: [deprecation] newInstance() in Class has been deprecated
                structurestart = (StructureStart)oclass.newInstance();
                                                       ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft_server\net\minecraft\world\gen\structure\MapGenStructureIO.java:81: warning: [deprecation] newInstance() in Class has been deprecated
                structurecomponent = (StructureComponent)oclass.newInstance();
                                                               ^

  where T is a type-variable:
    T extends Object declared in class Class
src\minecraft_server\net\minecraft\world\gen\structure\StructureMineshaftPieces.java:611: error: cannot find symbol
            for (lvt_5_1_ = 0; k < this.boundingBox.getXSize(); k = k + 4)
                 ^

  symbol:   variable lvt_5_1_
  location: class Room
src\minecraft_server\net\minecraft\world\storage\ThreadedFileIOBase.java:11: error: incompatible types: List<Object> cannot be converted to List<IThreadedFileIO>
    private List<IThreadedFileIO> threadedIOQueue = Collections.synchronizedList(Lists.newArrayList());
                                                                                ^

16 errors
29 warnings
==================

Initial server recompile failed, correct source then run updatemd5

**Comment by jLynx** [comment]
This is not an issue with MCPFixer. You dont need MCPFixer in order to decompile 1.8.8. There is already an MCP for that out there. MCP version v9.18 is for 1.8.8
http://www.modcoderpack.com/files/mcp918.zip

**Comment by 47e** [comment]
Thanks

**Comment by ThisTestUser** [comment]
MCPFixer is not meant to work with **any** version below 1.13.

**Comment by DaniboOrg** [comment]
I don't know what MCPFixer is so I'm sure that I don't use it, but I get the same error. Can you help?

**Comment by ThisTestUser** [comment]
You shouldn't get any error, as long as you download version 1.8.8 from the official website (http://www.modcoderpack.com/) and don't make any changes.

**Comment by Takkuxi** [comment]
i got a similar error but only with the MCP 1.8.8 here is my error:
> Applying patches
'runtime\bin\applydiff.exe -p1 -u -i ..\..\temp\temp.patch -d src\minecraft' failed : 1

== ERRORS FOUND ==

1 out of 1 hunk FAILED -- saving rejects to file 'net\minecraft\util\Cartesian.jav#'

**Comment by ThisTestUser** [comment]
The error isn't relevant to this repository, as it only supports 1.13 and above. If you really can't get it working, you could probably just do a search for "mcp 1.8.8" to see if anyone has uploaded it online.
